# Generated by Django 4.2.16 on 2025-03-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_test_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.RemoveField(
            model_name='test',
            name='created_at',
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='testsubmission',
            name='answers',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
